# coding=utf-8
import logging

from Commands.Command import Command


__author__ = 'kocsen'


class InternationalizationCommand(Command):
    """
    Command that will check if app is attempting to do internationalization
    """

    def __init__(self, app):
        self.app = app
        self.languages = get_languages()

    def execute(self):
        logging.info("Running Internationalization Command")

        num_languages = 0
        language_areas = []

        for folder_name in self.app.lang_dirs:
            split = folder_name.split("-")
            if len(split) > 1 and split[1] in self.languages:
                logging.debug('Found language internationalization: ' + split[1])
                num_languages += 1
                language_areas.append(self.languages[split[1]])

        if num_languages > 3:
            return True
        else:
            logging.info("Found no Internationalization attempt")
            return False


def get_languages():
    return {
        'aa': 'Afro-Asiatic',
        'ab': 'Northwest Caucasian',
        'ae': 'Indo-European',
        'af': 'Indo-European',
        'ak': 'Niger–Congo',
        'am': 'Afro-Asiatic',
        'an': 'Indo-European',
        'ar': 'Afro-Asiatic',
        'as': 'Indo-European',
        'av': 'Northeast Caucasian',
        'ay': 'Aymaran',
        'az': 'Turkic',
        'ba': 'Turkic',
        'be': 'Indo-European',
        'bg': 'Indo-European',
        'bh': 'Indo-European',
        'bi': 'Creole',
        'bm': 'Niger–Congo',
        'bn': 'Indo-European',
        'bo': 'Sino-Tibetan',
        'br': 'Indo-European',
        'bs': 'Indo-European',
        'ca': 'Indo-European',
        'ce': 'Northeast Caucasian',
        'ch': 'Austronesian',
        'co': 'Indo-European',
        'cr': 'Algonquian',
        'cs': 'Indo-European',
        'cu': 'Indo-European',
        'cv': 'Turkic',
        'cy': 'Indo-European',
        'da': 'Indo-European',
        'de': 'Indo-European',
        'dv': 'Indo-European',
        'dz': 'Sino-Tibetan',
        'ee': 'Niger–Congo',
        'el': 'Indo-European',
        'en': 'Indo-European',
        'eo': 'Constructed',
        'es': 'Indo-European',
        'et': 'Uralic',
        'eu': 'Language isolate',
        'fa': 'Indo-European',
        'ff': 'Niger–Congo',
        'fi': 'Uralic',
        'fj': 'Austronesian',
        'fo': 'Indo-European',
        'fr': 'Indo-European',
        'fy': 'Indo-European',
        'ga': 'Indo-European',
        'gd': 'Indo-European',
        'gl': 'Indo-European',
        'gn': 'Tupian',
        'gu': 'Indo-European',
        'gv': 'Indo-European',
        'ha': 'Afro-Asiatic',
        'he': 'Afro-Asiatic',
        'hi': 'Indo-European',
        'ho': 'Austronesian',
        'hr': 'Indo-European',
        'ht': 'Creole',
        'hu': 'Uralic',
        'hy': 'Indo-European',
        'hz': 'Niger–Congo',
        'ia': 'Constructed',
        'id': 'Austronesian',
        'ie': 'Constructed',
        'ig': 'Niger–Congo',
        'ii': 'Sino-Tibetan',
        'ik': 'Eskimo–Aleut',
        'io': 'Constructed',
        'is': 'Indo-European',
        'it': 'Indo-European',
        'iu': 'Eskimo–Aleut',
        'ja': 'Japonic',
        'jv': 'Austronesian',
        'ka': 'South Caucasian',
        'kg': 'Niger–Congo',
        'ki': 'Niger–Congo',
        'kj': 'Niger–Congo',
        'kk': 'Turkic',
        'kl': 'Eskimo–Aleut',
        'km': 'Austroasiatic',
        'kn': 'Dravidian',
        'ko': 'Koreanic',
        'kr': 'Nilo-Saharan',
        'ks': 'Indo-European',
        'ku': 'Indo-European',
        'kv': 'Uralic',
        'kw': 'Indo-European',
        'ky': 'Turkic',
        'la': 'Indo-European',
        'lb': 'Indo-European',
        'lg': 'Niger–Congo',
        'li': 'Indo-European',
        'ln': 'Niger–Congo',
        'lo': 'Tai–Kadai',
        'lt': 'Indo-European',
        'lu': 'Niger–Congo',
        'lv': 'Indo-European',
        'mg': 'Austronesian',
        'mh': 'Austronesian',
        'mi': 'Austronesian',
        'mk': 'Indo-European',
        'ml': 'Dravidian',
        'mn': 'Mongolic',
        'mr': 'Indo-European',
        'ms': 'Austronesian',
        'mt': 'Afro-Asiatic',
        'my': 'Sino-Tibetan',
        'na': 'Austronesian',
        'nb': 'Indo-European',
        'nd': 'Niger–Congo',
        'ne': 'Indo-European',
        'ng': 'Niger–Congo',
        'nl': 'Indo-European',
        'nn': 'Indo-European',
        'no': 'Indo-European',
        'nr': 'Niger–Congo',
        'nv': 'Dené–Yeniseian',
        'ny': 'Niger–Congo',
        'oc': 'Indo-European',
        'oj': 'Algonquian',
        'om': 'Afro-Asiatic',
        'or': 'Indo-European',
        'os': 'Indo-European',
        'pa': 'Indo-European',
        'pi': 'Indo-European',
        'pl': 'Indo-European',
        'ps': 'Indo-European',
        'pt': 'Indo-European',
        'qu': 'Quechuan',
        'rm': 'Indo-European',
        'rn': 'Niger–Congo',
        'ro': 'Indo-European',
        'ru': 'Indo-European',
        'rw': 'Niger–Congo',
        'sa': 'Indo-European',
        'sc': 'Indo-European',
        'sd': 'Indo-European',
        'se': 'Uralic',
        'sg': 'Creole',
        'si': 'Indo-European',
        'sk': 'Indo-European',
        'sl': 'Indo-European',
        'sm': 'Austronesian',
        'sn': 'Niger–Congo',
        'so': 'Afro-Asiatic',
        'sq': 'Indo-European',
        'sr': 'Indo-European',
        'ss': 'Niger–Congo',
        'st': 'Niger–Congo',
        'su': 'Austronesian',
        'sv': 'Indo-European',
        'sw': 'Niger–Congo',
        'ta': 'Dravidian',
        'te': 'Dravidian',
        'tg': 'Indo-European',
        'th': 'Tai–Kadai',
        'ti': 'Afro-Asiatic',
        'tk': 'Turkic',
        'tl': 'Austronesian',
        'tn': 'Niger–Congo',
        'to': 'Austronesian',
        'tr': 'Turkic',
        'ts': 'Niger–Congo',
        'tt': 'Turkic',
        'tw': 'Niger–Congo',
        'ty': 'Austronesian',
        'ug': 'Turkic',
        'uk': 'Indo-European',
        'ur': 'Indo-European',
        'uz': 'Turkic',
        've': 'Niger–Congo',
        'vi': 'Austroasiatic',
        'vo': 'Constructed',
        'wa': 'Indo-European',
        'wo': 'Niger–Congo',
        'xh': 'Niger–Congo',
        'yi': 'Indo-European',
        'yo': 'Niger–Congo',
        'za': 'Tai–Kadai',
        'zh': 'Sino-Tibetan',
        'zu': 'Niger–Congo',
    }
